* INSTALL: updated link to bugs, tool version numbers * TODO: removed easy HTML API generation todo item, it's done now; mention that CNI code won't be included in Classpath CVS for now since only gcj is using it * README: remove special mention of ORP * NEWS: add blurb about infrastructure improvements * HACKING: update automake, autoconf version numbers; remove mention of gcjh for compiling JNI libraries; updated gcj/jikes version numbers * lib/Makefile.am: distribute glibj.zip; uninstall no-zip case; separate resources target; avoid extra gen-classlist.sh calls; support DESTDIR * doc/api/Makefile.am: distribute HTML API documentation; install documentation in pkgdatadir/api; uninstall appropriately; support DESTDIR * resource/gnu/java/awt/peer/gtk/Makefile.am: add uninstall-local target; support DESTDIR * resource/java/security/Makefile.am: add uninstall-local target; support DESTDIR * javax/swing/Makefile.am: BoundedRangeModel missing .java extension * javax/transaction/xa/Makefile.am: Removed xa/ from filenames * java/awt/dnd/Makefile.am: added missing .java files to dist * java/net/Makefile.am: added missing .java files to dist * java/nio/channels/Makefile.am: added missing .java files to dist * javax/naming/Makefile.am: added missing .java files to dist * javax/naming/directory/Makefile.am: added missing .java files to dist * javax/naming/event/Makefile.am: new file * javax/naming/event/.cvsignore: new file * javax/naming/ldap/Makefile.am: new file * javax/naming/ldap/.cvsignore: new file * javax/naming/spi/Makefile.am: added missing .java files to dist * javax/sql/Makefile.am: added missing .java files to dist * javax/sql/.cvsignore: new file * javax/swing/plaf/Makefile.am: added missing .java files to dist * javax/swing/Makefile.am: added missing .java files to dist * Makefile.am: ignore errors during dist-hook * configure.in: add missing directory Makefiles to output; add check for 'date', 'cp', and 'mkdir' * acinclude.m4: remove check for 'find' and 'cp'

diff --git a/doc/api/Makefile.am b/doc/api/Makefile.am
--- a/doc/api/Makefile.am
+++ b/doc/api/Makefile.am
@@ -1,10 +1,46 @@
 if CREATE_API_DOCS
-all: Makefile create_xml create_catalog create_html
-else
-all: Makefile
+noinst_DATA = html
 endif
 
-.PHONY: create_xml create_catalog create_html
+EXTRA_DIST = classpath-copyright.xml
+
+dist-hook: 
+	-$(mkinstalldirs) $(distdir)
+	@if [ -d $(srcdir)/xslt ]; then \
+	  echo $(CP) -R $(srcdir)/xslt $(distdir); \
+	  $(CP) -R $(srcdir)/xslt $(distdir); \
+	fi
+	@if [ -d html ]; then \
+	  echo $(CP) -R html $(distdir); \
+	  $(CP) -R html $(distdir); \
+	else \
+	  echo "Error: did not configure --enable-gjdoc"; exit 1; \
+	fi
+
+htmllist := $(shell $(FIND) html | grep -v "^html$$")
+
+install-data-local:
+	$(mkinstalldirs) $(DESTDIR)$(pkgdatadir)/api
+	@for p in $(htmllist); do \
+	  f="`echo $$p | sed -e 's|^.*/||'`"; \
+	  if test -f "$$p"; then \
+	    echo " $(INSTALL_DATA) $$p $(DESTDIR)$(pkgdatadir)/api/$$f"; \
+	    $(INSTALL_DATA) $$p $(DESTDIR)$(pkgdatadir)/api/$$f; \
+	  elif test -d "$$p"; then \
+	    $(mkinstalldirs) $(DESTDIR)$(pkgdatadir)/api/$$f; \
+          fi; \
+        done
+
+uninstall-local:
+	@for p in $(htmllist); do \
+	  f="`echo $$p | sed -e 's|^.*/||'`"; \
+	  if test -f "$$p"; then \
+	    echo " rm -f $(DESTDIR)$(pkgdatadir)/api/$$f"; \
+	    rm -f $(DESTDIR)$(pkgdatadir)/api/$$f; \
+          fi; \
+        done
+
+html: create_xml create_catalog create_html
 
 packages := $(shell cd $(top_srcdir) && $(FIND) java javax -type d ! -regex .*CVS | tr '/' '.' )
 #| grep -v "^java\$" )
@@ -17,11 +53,12 @@ clean:
 	-rm -f gjdoc_rawcomment.cache
 
 create_xml:
-	-mkdir xml
+	-$(MKDIR) xml > /dev/null 2>&1
 	$(GJDOC) -sourcepath \
 		"$(top_srcdir):$(top_srcdir)/vm/reference" \
 		-doclet gnu.classpath.tools.doclets.xmldoclet.Driver \
 		-d xml $(packages) 
+	-touch create_xml
 
 create_catalog:
 	$(XMLCATALOG) --noout --create \
@@ -32,9 +69,10 @@ create_catalog:
 		http://www.gnu.org/software/cp-tools/dtd/ \
 		file:///usr/local/share/gjdoc/dtd/ \
 		gjdoccatalog.xml 
+	-touch create_catalog
 
 create_html:
-	-mkdir html
+	-$(MKDIR) html > /dev/null 2>&1
 	-$(CP) -Ru $(srcdir)/xslt/common html
 	$(XSLTPROC) \
 		--novalid \
@@ -45,4 +83,5 @@ create_html:
 		--param targetdir "'html'" \
 		"$(srcdir)/xslt/gjdocxml2html.xsl" \
 		"xml/index.xml"
+	-touch create_html
 
